export const PartnerDetails = {
  1: {
    id: 1,
    name: 'فندق اياس',
    arabicName: 'فندق اياس',
    email: 'auass_hotel@gmail.com',
    rating: 4.8,
    reviewCount: 25,
    followers: 156,
    description: 'تقديم خدمات حفلات فاخرة مع قاعات أنيقة',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1500 دينار',
    logo: require('../assets/partnersLogo/ayass_hotel.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-33-32.jpg') },
      { type: 'video', source: require('../assets/partners/ayass/videos/AQNmINbPD1QIRHWpmC6WInOSlHU7zTIf7uG_9V2sSLoZUZ9OgN12e6jHdzoLMVc.mp4') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-34-52.jpg') },
      { type: 'video', source: require('../assets/partners/ayass/videos/AQOyNzZURdZZLMIB89pFt_RBBmebsm3kwSetB6dsqf02H4uXidaK73eg1QKvMZF.mp4') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-34-57.jpg') },
      { type: 'video', source: require('../assets/partners/ayass/videos/AQPxqFy1fHYX5LHWz2P1TTA9UAnKlRi2sEmD_Knkr_V5AyUtJlFmWsHnpbwOHOq.mp4') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-35-03.jpg') },
      { type: 'video', source: require('../assets/partners/ayass/videos/AQP1PH4n0sWmIwtZu0kdSd0CqGSTY_cZOxEG_Jr1UjnkbwlQEBVyQH58ZiRx9ZzFqiGNFPCqAjCb1V.mp4') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-37-53.jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-38-01.jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-38-37.jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-39-40.jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-39-51.jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-40-11 (3).jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-40-11 (4).jpg') },
      { type: 'image', source: require('../assets/partners/ayass/photos/photo_2025-08-04_02-43-36.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 123 4567',
      address: 'شارع المدينة المنورة، عمان',
      website: 'www.auass-hotel.com'
    }
  },
  2: {
    id: 2,
    name: 'قاعات بيبك',
    arabicName: 'قاعات بيبك',
    email: 'bebek_restaurant@gmail.com',
    rating: 4.6,
    reviewCount: 42,
    followers: 203,
    description: 'قاعات بيبيك، أماكن الزفاف الخارجية',
    services: 'حفلات زفاف، حفلات خطوبة خارجية',
    location: 'عمان، الأردن',
    price: '1200 دينار',
    logo: require('../assets/partnersLogo/bebek.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-55-28.jpg') },
      { type: 'video', source: require('../assets/partners/bebek/videos/AQOfjogP1W49dG8QlvOnVeiuIeMBGSioqjSg8sfH5VTZttlVaRFKbg3T1boy8fLeberUNUcNVXLG.mp4') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-55-34.jpg') },
      { type: 'video', source: require('../assets/partners/bebek/videos/AQPkkeHQHXzHaHQZLyiyWyMtxYnd_8EwcSnZfLobbzhJvURDxbirmnosICIjfRVpF4yQZ.mp4') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-55-39.jpg') },
      { type: 'video', source: require('../assets/partners/bebek/videos/AQPSpwLPOrfpoouQ2y43aylLHI_SqidKhosiu_6WF1AqYdoaKaREbCDrElmQ1dZFk8ep5udGGqQ.mp4') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-55-44.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-56-25.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-56-29.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-56-35.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-56-40.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-56-45.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-57-27.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-57-32.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-57-38.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-57-43.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-58-20.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-58-30.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-58-34.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_02-59-52.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_03-00-47.jpg') },
      { type: 'image', source: require('../assets/partners/bebek/photos/photo_2025-08-04_03-06-04.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 234 5678',
      address: 'طريق المطار، عمان',
      website: 'https://www.instagram.com/bebekhalls/#'
    }
  },
  3: {
    id: 3,
    name: 'قاعة النعمان',
    arabicName: 'قاعة النعمان',
    email: 'alnuman_hall@gmail.com',
    rating: 4.9,
    reviewCount: 38,
    followers: 189,
    description: 'قاعة حفلات كلاسيكية مع حديقة خارجية',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1800 دينار',
    logo: require('../assets/partnersLogo/alnuman.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-09-51.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-11-38.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-12-30.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-06-45.jpg') },
      { type: 'video', source: require('../assets/partners/alnuman/vidoes/alnuman_vidoe1.mp4') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-07-26.jpg') },
      { type: 'video', source: require('../assets/partners/alnuman/vidoes/alnuman_video2.mp4') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-08-25.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-09-37.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-09-42.jpg') },
      { type: 'image', source: require('../assets/partners/alnuman/photos/photo_2025-08-04_03-09-31.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 345 6789',
      address: 'شارع الجامعة، عمان',
      website: 'www.alnuman-hall.com'
    }
  },
  4: {
    id: 4,
    name: 'شفا بيرل',
    arabicName: 'شفا بيرل',
    email: 'shafa_pearl@gmail.com',
    rating: 4.7,
    reviewCount: 31,
    followers: 167,
    description: 'قاعة حفلات فاخرة مع إطلالة رائعة',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1600 دينار',
    logo: require('../assets/partnersLogo/shafa_pearl.jpg'),
    gallery: [
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQMdsvjIPPxumQsO_oeHMUVhX8fCFI_8_G_zCzgEYiwiTFzRLK01RbGVEd06yNQ.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQNTfKfAvQdy5TmfYXii2uu5Wf3rYd4C_KV0c7rP39MVChHaGP5Jpokfo3S7i4G.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQNXaBSpd9xSpdd8q2SQBRveyMIoLUg7xrXc8_iWhFfaV2xyWNSI1BbGxxoPlKj.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQObPpwrgQiqbIPgdqJNxL2Fdn4oBP4Kxu0FPJkhZMWkNPjK6cYg0dk_2M551zTlxSB6H.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQOmFOtc87MutUvAwfpzcoBnuLFV2AeQOteOcv1dKxVUpJGRCSaCED_eO9UvJluDT9AfsN0yYTDg1.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQOPJfENk3a2QRtCNoZQO6sXqQZqn_Pf3i_oyDKsaXeIW6emC6FsQUXzXUNOXsf.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQP_l6KbOKMyrSpZPFmj8zHSKeXo2tNt7vsXnPl7imf5rJsvc_d6tjodLncWkrm.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQPIpJd1HtPRJ7xDSuCeGCEZMEy1BlmfAcZKwNJMqsxmyXkh9kC1sNv6Z_JR9i6.mp4') },
      { type: 'video', source: require('../assets/partners/shafa_pearl/videos/AQPLtQuSHTsUcXdI0TvTHRiVERWmiN_OLFbLMtgNx3Fvu_YdZNeOsH6Nhgbc3LG.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 456 7890',
      address: 'شارع الرابية، عمان',
      website: 'www.shafa-pearl.com'
    }
  },
  5: {
    id: 5,
    name: 'وايت هول',
    arabicName: 'وايت هول',
    email: 'white_hall@gmail.com',
    rating: 4.8,
    reviewCount: 28,
    followers: 145,
    discount: '20%',
    description: 'قاعة حفلات أنيقة بتصميم كلاسيكي',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1400 دينار',
    logo: require('../assets/partnersLogo/white_hall.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-51-41.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-51-47.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-51-53.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-51-59.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-13.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-22.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-37.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-45.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-51.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-52-58.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-53-03.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-53-12.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-53-22.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-53-27.jpg') },
      { type: 'image', source: require('../assets/partners/white_hall/photos/photo_2025-08-09_02-53-32.jpg') },
      { type: 'video', source: require('../assets/partners/white_hall/videos/1429005061205659107.mp4') },
      { type: 'video', source: require('../assets/partners/white_hall/videos/AQOlpNR7UVWiGhgWI4hMNZb37ZHeyr1Pkqv_BvwHKQ3_XIPqO64GCeiCkipWtRuHvGdp3b.mp4') },
      { type: 'video', source: require('../assets/partners/white_hall/videos/AQOVkDe0xgUCqNt7_TuiycS1OaF7kiFejYmu_x1uzmx3uoqEhxAGIiLLNRB9JuO.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 567 8901',
      address: 'شارع الصويفية، عمان',
      website: 'www.white-hall.com'
    }
  },
  6: {
    id: 6,
    name: 'سينسيشن',
    arabicName: 'سينسيشن',
    email: 'sensation@gmail.com',
    rating: 4.6,
    reviewCount: 35,
    followers: 178,
    discount: '30%',
    description: 'قاعة حفلات عصرية مع تقنيات متطورة',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1300 دينار',
    logo: require('../assets/partnersLogo/sensation.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-21-38.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-21-49.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-21-54.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-21-58.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-03.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-07.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-43.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-50.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-55.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-22-59.jpg') },
      { type: 'image', source: require('../assets/partners/sensation/photos/photo_2025-08-09_03-23-04.jpg') },
      { type: 'video', source: require('../assets/partners/sensation/videos/AQMeHOoGHExvPUu34s610JwnJTkfPbLC_GGczPIGfpYQIiIUXBc6SlQk2OuJAWR.mp4') },
      { type: 'video', source: require('../assets/partners/sensation/videos/AQMlY9tXn3feI3kqha0KheE_NDNsEGTTleQDu1XT6VVOyXHIwCku6tfKHNAn8riRWPjmDVoDwz.mp4') },
      { type: 'video', source: require('../assets/partners/sensation/videos/AQN9LkDsc4kQw9xUbSlGwSuXIho4Z7Z9uxQnTrrGDrJgEolnmtPirMWxvsJsVE_.mp4') },
      { type: 'video', source: require('../assets/partners/sensation/videos/AQPeAoogTnLsR0hCAZIv2WNiBdF4QMGjkFgaeIJl0Xjr8NcADqiRAdhPDHmvpWECSmHwd.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 678 9012',
      address: 'شارع عبدون، عمان',
      website: 'www.sensation.com'
    }
  },
  7: {
    id: 7,
    name: 'كراون',
    arabicName: 'كراون',
    email: 'crown@gmail.com',
    rating: 4.9,
    reviewCount: 42,
    followers: 198,
    description: 'قاعة حفلات فاخرة مع خدمة متميزة',
    services: 'حفلات زفاف، حفلات خطوبة، حفلات أعياد ميلاد',
    location: 'عمان، الأردن',
    price: '1700 دينار',
    logo: require('../assets/partnersLogo/crown.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-07-56.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-09-10.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-09-45.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-09-45 (1).jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-09-50.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-09-56.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-10-02.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-10-17.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-10-48.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-10-54.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-11-55.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-12-00.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-12-05.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-12-11.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-13-24.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-13-32.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-15-14.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-15-50.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-16-50.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-16-54.jpg') },
      { type: 'image', source: require('../assets/partners/crown/photos/photo_2025-08-05_01-17-00.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 789 0123',
      address: 'شارع المدينة المنورة، عمان',
      website: 'www.crown.com'
    }
  },
  
  // Clothing Services
  8: {
    id: 8,
    name: 'بيانكا روزا',
    arabicName: 'بيانكا روزا',
    email: 'beanka_rosa@gmail.com',
    rating: 4.9,
    reviewCount: 98,
    discount: '10%',
    followers: 345,
    description: 'أزياء عرائس فاخرة مع خياطة مخصصة',
    services: 'أزياء عرائس، فساتين زفاف، خياطة مخصصة',
    location: 'عمان، الأردن',
    price: '200 دينار',
    logo: require('../assets/partnersLogo/beanka_rosa.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-28-52.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-29-26.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-29-34.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-29-39.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-29-45.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-30-22.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-30-28.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-30-32.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-31-03.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-31-10.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-31-14.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-31-21.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-32-03.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-32-08.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-32-50.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-33-20.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-33-54.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-33-59.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-34-31.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-34-36.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/photo_2025-08-05_00-34-42.jpg') },
      { type: 'image', source: require('../assets/partners/beanka_rosa/photos/dress1.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 789 0123',
      address: 'شارع المدينة المنورة، عمان',
      website: 'www.beanka-rosa.com'
    }
  },
  9: {
    id: 9,
    name: 'دي كلاس',
    arabicName: 'دي كلاس',
    email: 'di_class@gmail.com',
    rating: 4.7,
    reviewCount: 54,
    discount: '35%',
    followers: 267,
    description: 'أزياء عرائس كلاسيكية وعصرية',
    services: 'أزياء عرائس، فساتين زفاف، خياطة مخصصة',
    location: 'عمان، الأردن',
    price: '650 دينار',
    logo: require('../assets/partnersLogo/di_class.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/di_class/photos/04871800712-p.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/05644063800-p.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/05732173401-p.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/05747462801-p.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/benjamin-r-Ci_fZ5cL9Jo-unsplash.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/businessman-brown-suit-studio-portrait.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/portrait-happy-smiling-young-businessman-blue-suit-isolated-white-wall.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/portrait-happy-smiling-young-businessman-brown-suit-isolated-white-wall.jpg') },
      { type: 'image', source: require('../assets/partners/di_class/photos/suit1.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 890 1234',
      address: 'شارع الصويفية، عمان',
      website: 'www.di-class.com'
    }
  },
  10: {
    id: 10,
    name: 'سبيس فور مان',
    arabicName: 'سبيس فور مان',
    email: 'space_for_man@gmail.com',
    rating: 4.8,
    reviewCount: 73,
    discount: '40%',
    followers: 412,
    description: 'تصميم أزياء مخصصة للعرائس',
    services: 'أزياء عرائس، فساتين زفاف، خياطة مخصصة',
    location: 'عمان، الأردن',
    price: '950 دينار',
    logo: require('../assets/partnersLogo/space_for_man.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-44-44.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-45-09.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-46-12.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-46-40.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-47-15.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-47-48.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-48-22.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-49-32.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-50-44.jpg') },
      { type: 'image', source: require('../assets/partners/space_for_man/photos/photo_2025-08-05_02-51-32.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 901 2345',
      address: 'شارع عبدون، عمان',
      website: 'www.space-for-man.com'
    }
  },
  11: {
    id: 11,
    name: 'جازمن فاشن',
    arabicName: 'جازمن فاشن',
    email: 'jasmine_fashion@gmail.com',
    rating: 4.8,
    reviewCount: 73,
    followers: 389,
    description: 'تصميم أزياء مخصصة للعرائس',
    services: 'أزياء عرائس، فساتين زفاف، خياطة مخصصة',
    location: 'عمان، الأردن',
    price: '950 دينار',
    logo: require('../assets/partnersLogo/jasmine_fashion.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-37-45.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-39-07.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-39-28.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-39-46.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-40-48.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-41-44.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-42-07.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-42-12.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-42-18.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-42-44.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-43-05.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-43-10.jpg') },
      { type: 'image', source: require('../assets/partners/jasmin_fashion/photos/photo_2025-08-09_02-43-30.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 012 3456',
      address: 'شارع الرابية، عمان',
      website: 'www.jasmine-fashion.com'
    }
  },
  12: {
    id: 12,
    name: 'تاليا دريس',
    arabicName: 'تاليا دريس',
    email: 'talyas_dress@gmail.com',
    rating: 4.2,
    reviewCount: 68,
    discount: '30%',
    followers: 356,
    description: 'تصميم أزياء مخصصة للعرائس',
    services: 'أزياء عرائس، فساتين زفاف، خياطة مخصصة',
    location: 'عمان، الأردن',
    price: '950 دينار',
    logo: require('../assets/partnersLogo/talyas_dress.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-05_03-04-10.jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-05_03-04-10 (2).jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-05_03-05-17.jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-05_03-05-42.jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-09_03-01-52.jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-09_03-02-57.jpg') },
      { type: 'image', source: require('../assets/partners/talyas_dress/photos/photo_2025-08-09_03-03-44.jpg') },
      { type: 'video', source: require('../assets/partners/talyas_dress/videos/AQNO7Wnr61YOjdJdkS24t1T15rodf3ceVSu7qWg9L2h5Xr0f1JvdPFaaFwywl2V.mp4') },
      { type: 'video', source: require('../assets/partners/talyas_dress/videos/AQNoRRHyvfclcU0F_qS2cY4hjtSwyQynTzm_6gz6y0D9XyyQIYlmwLmw71BVTXu.mp4') },
      { type: 'video', source: require('../assets/partners/talyas_dress/videos/AQPDxmYLNI3DqXj851R2NkrCn_WCKwl8zZAFjOEfDVSUCs39NuaTm8uNk7U0NkQ.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 123 4567',
      address: 'شارع المدينة المنورة، عمان',
      website: 'www.talyas-dress.com'
    }
  },

  // Car Rental Services
  13: {
    id: 13,
    name: 'ديفا كارز',
    arabicName: 'ديفا كارز',
    email: 'diva_cars@gmail.com',
    rating: 4.8,
    reviewCount: 89,
    discount: '15%',
    followers: 523,
    description: 'سيارات زفاف فاخرة مع سائق محترف',
    services: 'تأجير سيارات زفاف، سيارات فاخرة، سائق محترف',
    location: 'عمان، الأردن',
    price: '300 دينار',
    logo: require('../assets/partnersLogo/diva_cars.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-30-47.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-31-07.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-31-12.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-31-17.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-31-24.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-31-46.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-32-11.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-32-16.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-32-21.jpg') },
      { type: 'image', source: require('../assets/partners/diva_cars/photos/photo_2025-08-09_03-36-00.jpg') },
      { type: 'video', source: require('../assets/partners/diva_cars/vidoes/AQMYh3HRj2AO3dEu_npCG5bSfoPgUc6EO8X0dX8dEXWYTcnVaDcJOVLZ_qjExSI.mp4') },
      { type: 'video', source: require('../assets/partners/diva_cars/vidoes/AQOyvL_rGfisQ7n_v89vUjmimgzh2kIdoytr5tmCDMzd2Ip5IRBaRAJ9J_4NZsSdrX34.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 234 5678',
      address: 'شارع المطار، عمان',
      website: 'www.diva-cars.com'
    }
  },
  14: {
    id: 14,
    name: 'ايليت ورد',
    arabicName: 'ايليت ورد',
    email: 'elite_world@gmail.com',
    rating: 4.9,
    reviewCount: 76,
    followers: 445,
    description: 'سيارات زفاف كلاسيكية وعصرية',
    services: 'تأجير سيارات زفاف، سيارات كلاسيكية، سائق محترف',
    location: 'عمان، الأردن',
    price: '450 دينار',
    logo: require('../assets/partnersLogo/elite_world.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-32-53.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-02.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-06.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-29.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-32.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-37.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-48-57.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/photo_2025-08-09_03-50-14.jpg') },
      { type: 'image', source: require('../assets/partners/elite_world/photos/car1.png') },
    ],
    contactInfo: {
      phone: '+962 79 345 6789',
      address: 'شارع الجامعة، عمان',
      website: 'www.elite-world.com'
    }
  },
  // Makeup Artists
  15: {
    id: 15,
    name: 'لجين سعد الدين',
    arabicName: 'لجين سعد الدين',
    email: 'lujain_saadaldeen@gmail.com',
    rating: 4.9,
    reviewCount: 45,
    discount: '35%',
    followers: 234,
    description: 'تجميل عرائس احترافي مع خبرة 10 سنوات',
    services: 'تجميل عرائس، مكياج احتفالي، تجميل عروس',
    location: 'عمان، الأردن',
    price: '200 دينار',
    logo: require('../assets/partnersLogo/lujain_saadaldeen.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-02-30.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-03-04.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-03-30.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-03-34.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-04-07.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-04-12.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-04-17.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-04-43.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-05-43.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-05-48.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-06-23.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-06-59.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-07-25.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-07-30.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-08-20.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-08-48.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-09-20.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-09-59.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-10-58.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-11-24.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-12-00.jpg') },
      { type: 'image', source: require('../assets/partners/lujain_saadaldein/photos/photo_2025-08-05_00-12-33.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 456 7890',
      address: 'شارع الرابية، عمان',
      website: 'www.lujain-makeup.com'
    }
  },
  16: {
    id: 16,
    name: 'بوب',
    arabicName: 'بوب',
    email: 'bob_makeup@gmail.com',
    rating: 4.7,
    reviewCount: 38,
    followers: 187,
    description: 'خدمات تجميل شاملة للعرائس',
    services: 'تجميل عرائس، مكياج احتفالي، تجميل عروس',
    location: 'عمان، الأردن',
    price: '180 دينار',
    logo: require('../assets/partnersLogo/bob.jpg'),
    gallery: [
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQMCde9dyfTsQ_uDQdMkKeTpKz_5WwQj0ukbaDjIyTNIVJGcMYWE0amZ3k1z6wNE9fSJ.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQMCIcZLzYxveglOelZuAJwhBIZyQelmA2OEDbPwPCaHJPf8F6uFlk1QmMay3sM.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQMnvCPGuURGTMJepUCLIht0TXS0hWt8zzOcPXW4G7n3KloKh9k9xzI6ZGuwMhp.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQO1dJ6GEApaufEk_eTvO3cguzSFSb5BPMr5Ys_ZCpK1zWQrRJb7EZIrMAfybtU.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQOBkYUUk2q1nAb9TpGLKZlhEvYZD4KThSA0fu6jCf4bju6TqLBRRTXekdPuuYi.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQOwH5JeM4YUIVKXLUs1LsUYCT7eRcKZ5HpzvlfWD5ZZkDzyrs8TC55cLD539PZ.mp4') },
      { type: 'video', source: require('../assets/partners/bob/vidoes/AQPozhFsjyTF6tfv4zHpm_3S7XOpk3gGOFTWkKcTOy1BLodvJqStBtLtx4qFXyb.mp4') },
    ],
    contactInfo: {
      phone: '+962 79 567 8901',
      address: 'شارع الصويفية، عمان',
      website: 'www.bob-makeup.com'
    }
  },
  17: {
    id: 17,
    name: 'سونا جيرمي',
    arabicName: 'سونا جيرمي',
    email: 'sona_jermi@gmail.com',
    rating: 4.8,
    reviewCount: 52,
    followers: 298,
    description: 'تجميل عرائس فاخر مع منتجات عالمية',
    services: 'تجميل عرائس، مكياج احتفالي، تجميل عروس',
    location: 'عمان، الأردن',
    price: '220 دينار',
    logo: require('../assets/partnersLogo/sona_jermi.jpg'),
    gallery: [
      { type: 'image', source: require('../assets/partners/sona_jermi/photos/photo_2025-08-09_03-09-38.jpg') },
      { type: 'image', source: require('../assets/partners/sona_jermi/photos/photo_2025-08-09_03-12-39.jpg') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQMQG2u_Fve_jAxuH_4gFbSuaA85ZCdNbEf3oxDOeHNwWxNdBr5pDEvmCzU4jff.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQMZ43wGbSteC5WGlDeroTjc5U1457IbVOlOX8EIvMZclRvuQ0LIE88zszOI9qs.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQNJ9lBUZg7lhTSkPqwfe0PzsuU2ITdminkwMRFrXsDp1Qb5nbZPMujbba83FZh.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQNSK6ubktksbI1LrGgk0Ekk8w_2ZQxjGSLnzHGV29qhKAezM_57lBEApt8gE2v.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQOnIlNK88blNa_4tMk3ygbvVezjaAG7hx1vTExtjDABpyeM73XIG_USuh_DhwUd.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQOunAsYev4AjJakPLpp9FLWLLkOQzLlSsTVKuEsSSr2vVpvR34dEl8Fdz61TV3ugqihNfZ.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQP9kH4QMscWI5z_Poo8uJsfJ0u_phL8FBAwrxFWpSymB3CwHfp6eh4K07df_QB.mp4') },
      { type: 'video', source: require('../assets/partners/sona_jermi/vidoes/AQPOmM8_9Enn8QRAYHcjMHMaQJ9q1CXkchqKXKboMqgh28Kt4g5NTj98zZ2D0b3.mp4') },
      { type: 'image', source: require('../assets/partners/sona_jermi/photos/makeup1.jpg') },
    ],
    contactInfo: {
      phone: '+962 79 678 9012',
      address: 'شارع عبدون، عمان',
      website: 'www.sona-jermi.com'
    }
  },

  
  
};
